"""add_generated_contracts_table

Revision ID: 1adb51cc57e8
Revises: 541ded1cb879
Create Date: 2025-09-27 02:22:36.062236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1adb51cc57e8'
down_revision: Union[str, Sequence[str], None] = '541ded1cb879'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_contracts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contract_type', sa.Enum('TOKEN', 'NFT', 'DEFI', 'MARKETPLACE', 'GOVERNANCE', 'UTILITY', 'CUSTOM', name='contracttype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('network', sa.Enum('MAINNET', 'TESTNET', 'EMULATOR', name='networktype'), nullable=False),
    sa.Column('generation_method', sa.Enum('AI_ASSISTED', 'TEMPLATE_BASED', 'MANUAL', name='generationmethod'), nullable=True),
    sa.Column('requirements_text', sa.Text(), nullable=True),
    sa.Column('context_used', sa.JSON(), nullable=True),
    sa.Column('contract_code', sa.Text(), nullable=False),
    sa.Column('project_directory', sa.String(length=500), nullable=False),
    sa.Column('contract_file_path', sa.String(length=500), nullable=False),
    sa.Column('has_transactions', sa.Boolean(), nullable=True),
    sa.Column('has_scripts', sa.Boolean(), nullable=True),
    sa.Column('has_tests', sa.Boolean(), nullable=True),
    sa.Column('flow_json_config', sa.JSON(), nullable=True),
    sa.Column('token_metadata', sa.JSON(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('context_files_count', sa.Integer(), nullable=True),
    sa.Column('context_size_chars', sa.Integer(), nullable=True),
    sa.Column('generation_time_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generated_contracts')
    # ### end Alembic commands ###
