"""Initial database schema

Revision ID: 541ded1cb879
Revises: 
Create Date: 2025-09-26 01:13:18.771228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '541ded1cb879'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentation_knowledge_base',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=1000), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.Enum('LANGUAGE_SPEC', 'API_REFERENCE', 'TUTORIAL', 'EXAMPLE', name='contenttype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding_vector', sa.JSON(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('persona_type', sa.Enum('EXPERT', 'INTERMEDIATE', 'BEGINNER', 'NON_TECHNICAL', name='personatype'), nullable=False),
    sa.Column('flow_account_address', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('data_retention_consent', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flow_account_address')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('contract_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('input_type', sa.Enum('CDC_FILE', 'SOL_FILE', 'NATURAL_LANGUAGE', 'MIXED', name='inputtype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('pre_conditions', sa.JSON(), nullable=True),
    sa.Column('post_conditions', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='submissionstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_data_controls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('data_retention_preference', sa.Enum('KEEP_ALL', 'DELETE_AFTER_30D', 'DELETE_IMMEDIATELY', name='dataretentionpreference'), nullable=True),
    sa.Column('learning_consent', sa.Boolean(), nullable=True),
    sa.Column('deletion_requests', sa.JSON(), nullable=True),
    sa.Column('last_data_access', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('generated_configurations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('config_content', sa.JSON(), nullable=False),
    sa.Column('generated_contract_code', sa.Text(), nullable=False),
    sa.Column('validation_status', sa.Enum('VALID', 'INVALID', 'PENDING', name='validationstatus'), nullable=True),
    sa.Column('validation_errors', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['contract_submissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id')
    )
    op.create_table('deployment_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('config_id', sa.UUID(), nullable=False),
    sa.Column('deployment_id', sa.String(length=255), nullable=True),
    sa.Column('network', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', 'TIMEOUT', 'VALIDATION_ERROR', name='deploymentstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('transaction_hash', sa.String(length=255), nullable=True),
    sa.Column('gas_used', sa.Integer(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=False),
    sa.Column('log_content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['generated_configurations.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['contract_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction_proposals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('config_id', sa.UUID(), nullable=False),
    sa.Column('transaction_type', sa.Enum('DEPLOY', 'UPDATE', 'INTERACT', name='transactiontype'), nullable=False),
    sa.Column('transaction_data', sa.JSON(), nullable=False),
    sa.Column('estimated_gas', sa.Integer(), nullable=False),
    sa.Column('user_approval_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approvalstatus'), nullable=True),
    sa.Column('signed_transaction', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['generated_configurations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_feedback_loops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('pattern_type', sa.Enum('ERROR_PATTERN', 'SUCCESS_PATTERN', 'OPTIMIZATION_OPPORTUNITY', name='patterntype'), nullable=False),
    sa.Column('insights', sa.JSON(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('applied_to_generation', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['log_id'], ['deployment_logs.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['contract_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('learning_feedback_loops')
    op.drop_table('transaction_proposals')
    op.drop_table('deployment_logs')
    op.drop_table('generated_configurations')
    op.drop_table('user_data_controls')
    op.drop_table('contract_submissions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('documentation_knowledge_base')
    # ### end Alembic commands ###
