"""Add CLI logs table

Revision ID: 7f2899f3f086
Revises: 1adb51cc57e8
Create Date: 2025-09-28 01:10:14.796936

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7f2899f3f086'
down_revision = '1adb51cc57e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum for status
    cli_log_status = sa.Enum('SUCCESS', 'FAILED', 'TIMEOUT', 'PENDING', name='cli_log_status')
    cli_log_status.create(op.get_bind())

    op.create_table('cli_logs',
        sa.Column('id', sa.UUID(as_uuid=True), nullable=False),
        sa.Column('session_id', sa.UUID(as_uuid=True), nullable=False),
        sa.Column('command', sa.String(length=500), nullable=False),
        sa.Column('full_output', sa.Text(), nullable=False),
        sa.Column('extracted_data', sa.JSON(), nullable=True),
        sa.Column('start_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('end_time', sa.DateTime(), nullable=True),
        sa.Column('duration_ms', sa.Integer(), nullable=True),
        sa.Column('status', cli_log_status, nullable=False, server_default='PENDING'),
        sa.Column('user_id', sa.UUID(as_uuid=True), nullable=True),
        sa.Column('contract_submission_id', sa.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(['contract_submission_id'], ['contract_submissions.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cli_logs_contract_submission_id'), 'cli_logs', ['contract_submission_id'], unique=False)
    op.create_index(op.f('ix_cli_logs_session_id'), 'cli_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_cli_logs_user_id'), 'cli_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cli_logs_user_id'), table_name='cli_logs')
    op.drop_index(op.f('ix_cli_logs_session_id'), table_name='cli_logs')
    op.drop_index(op.f('ix_cli_logs_contract_submission_id'), table_name='cli_logs')
    op.drop_table('cli_logs')
    cli_log_status = sa.Enum('SUCCESS', 'FAILED', 'TIMEOUT', 'PENDING', name='cli_log_status')
    cli_log_status.drop(op.get_bind())
    # ### end Alembic commands ###
