"""Add IPFS storage fields to GeneratedConfiguration

Revision ID: 9494951be3f8
Revises: 109bb47db95b
Create Date: 2025-09-30 04:18:05.786009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9494951be3f8'
down_revision: Union[str, Sequence[str], None] = '109bb47db95b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_configurations', sa.Column('ipfs_cid', sa.String(length=255), nullable=True))
    op.add_column('generated_configurations', sa.Column('ipfs_pin_id', sa.String(length=255), nullable=True))
    op.add_column('generated_configurations', sa.Column('ipfs_uploaded_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('generated_configurations', sa.Column('ipfs_metadata', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_generated_configurations_ipfs_cid'), 'generated_configurations', ['ipfs_cid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_configurations_ipfs_cid'), table_name='generated_configurations')
    op.drop_column('generated_configurations', 'ipfs_metadata')
    op.drop_column('generated_configurations', 'ipfs_uploaded_at')
    op.drop_column('generated_configurations', 'ipfs_pin_id')
    op.drop_column('generated_configurations', 'ipfs_cid')
    # ### end Alembic commands ###
