"""add missing cli_logs on current DB

Revision ID: f4e4aaade729
Revises: 7f2899f3f086
Create Date: 2025-09-28 01:35:41.378213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4e4aaade729'
down_revision: Union[str, Sequence[str], None] = '7f2899f3f086'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cli_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('command', sa.String(length=500), nullable=False),
    sa.Column('full_output', sa.Text(), nullable=False),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', 'TIMEOUT', 'PENDING', name='clilogstatus'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('contract_submission_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['contract_submission_id'], ['contract_submissions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cli_logs_session_id'), 'cli_logs', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cli_logs_session_id'), table_name='cli_logs')
    op.drop_table('cli_logs')
    # ### end Alembic commands ###
