"""
Contract-related data models.
"""

from sqlalchemy import Column, String, DateTime, JSON, Text, ForeignKey, Enum
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from .database import Base
import enum
import uuid


class InputType(str, enum.Enum):
    """Contract input types."""
    CDC_FILE = "CDC_FILE"
    SOL_FILE = "SOL_FILE"
    NATURAL_LANGUAGE = "NATURAL_LANGUAGE"
    MIXED = "MIXED"


class SubmissionStatus(str, enum.Enum):
    """Contract submission status."""
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class ValidationStatus(str, enum.Enum):
    """Configuration validation status."""
    VALID = "VALID"
    INVALID = "INVALID"
    PENDING = "PENDING"


class ContractSubmission(Base):
    """Represents a user's contract input for processing."""

    __tablename__ = "contract_submissions"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=False)
    input_type = Column(Enum(InputType), nullable=False)
    content = Column(Text, nullable=False)
    pre_conditions = Column(JSON, nullable=True)
    post_conditions = Column(JSON, nullable=True)
    status = Column(Enum(SubmissionStatus), default=SubmissionStatus.PENDING)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    processed_at = Column(DateTime(timezone=True), nullable=True)

    # Relationships
    user = relationship("User", back_populates="contract_submissions")
    deployment_logs = relationship("DeploymentLog", back_populates="contract_submission")
    generated_config = relationship("GeneratedConfiguration", back_populates="contract_submission", uselist=False)
    cli_logs = relationship("CLILog", back_populates="contract_submission", cascade="all, delete-orphan")

    def __repr__(self):
        return f"<ContractSubmission(id={self.id}, input_type={self.input_type}, status={self.status})>"


class GeneratedConfiguration(Base):
    """flow.json compatible configuration files generated by LLM."""

    __tablename__ = "generated_configurations"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    submission_id = Column(UUID(as_uuid=True), ForeignKey("contract_submissions.id"), nullable=False, unique=True)
    config_content = Column(JSON, nullable=False)
    generated_contract_code = Column(Text, nullable=False)
    validation_status = Column(Enum(ValidationStatus), default=ValidationStatus.PENDING)
    validation_errors = Column(JSON, nullable=True)
    
    # IPFS Storage fields
    ipfs_cid = Column(String(255), nullable=True, index=True)  # IPFS Content Identifier
    ipfs_pin_id = Column(String(255), nullable=True)  # Pinata pin ID for management
    ipfs_uploaded_at = Column(DateTime(timezone=True), nullable=True)
    ipfs_metadata = Column(JSON, nullable=True)  # Additional IPFS metadata
    
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    last_modified = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

    # Relationships
    contract_submission = relationship("ContractSubmission", back_populates="generated_config")
    deployment_logs = relationship("DeploymentLog", back_populates="generated_configuration")
    transaction_proposals = relationship("TransactionProposal", back_populates="generated_configuration")

    def __repr__(self):
        return f"<GeneratedConfiguration(id={self.id}, validation_status={self.validation_status})>"